const { pdfRefForDocumentId } = require("../originalDocuments");

function toPublicChecklist(checklist, { originalStorageRoot } = {}) {
  if (!checklist) return null;
  return {
    id: checklist.id,
    title: checklist.title,
    aliases: Array.isArray(checklist.aliases) ? checklist.aliases : [],
    sections: Array.isArray(checklist.sections) ? checklist.sections : [],
    active: checklist.status === "active" && checklist.active !== false,
    status: checklist.status === "needs_review" ? "needs_review" : "active",
    reviewReasons: Array.isArray(checklist.validation?.problems)
      ? checklist.validation.problems.filter((code) => /^[a-z-]+$/u.test(code))
      : [],
    autoGenerated: checklist.autoGenerated === true,
    editedByAdmin: checklist.editedByAdmin === true,
    source: {
      filename: checklist.source?.filename || "",
      page: Number(checklist.source?.page || checklist.page || 0) || null,
      pdfRef: pdfRefForDocumentId(String(checklist.documentId || ""), {
        storageRoot: originalStorageRoot,
      }),
    },
  };
}

module.exports = { toPublicChecklist };
