const { pdfRefForDocumentId } = require("../originalDocuments");
const { searchAliasesFor } = require("./commonNames");
const { synonymNameVariants } = require("../synonyms");

function searchNames(checklist, synonymGroups = []) {
  const aliases = Array.isArray(checklist.aliases) ? checklist.aliases : [];
  const everyday = searchAliasesFor(checklist);
  // Active synonyms (동의어 사전): the same names with one word swapped.
  return [
    ...everyday,
    ...synonymNameVariants([...aliases, ...everyday], synonymGroups),
  ];
}

// How a checklist of a newly uploaded edition compares with the earlier one.
const VERSION_REVIEW_CODES = new Set([
  "changed",
  "new",
  "ambiguous",
  "previous-not-public",
  "previous-unverifiable",
]);

function versionResult(checklist = {}) {
  const value = checklist.versionMatch?.result;
  return typeof value === "string" && /^[a-z-]+$/u.test(value) ? value : null;
}

function reviewReasons(checklist = {}) {
  const codes = Array.isArray(checklist.validation?.problems)
    ? checklist.validation.problems.filter((code) => /^[a-z-]+$/u.test(code))
    : [];
  const version = versionResult(checklist);
  if (checklist.status === "needs_review" && VERSION_REVIEW_CODES.has(version))
    codes.push(`version-${version}`);
  // A new automatic checklist that passed the source comparison still waits
  // for an administrator.
  if (
    !codes.length &&
    checklist.status === "needs_review" &&
    checklist.autoVerified
  )
    return ["auto-generated"];
  return codes;
}

function toPublicChecklist(
  checklist,
  { originalStorageRoot, synonymGroups = [] } = {}
) {
  if (!checklist) return null;
  return {
    id: checklist.id,
    title: checklist.title,
    aliases: Array.isArray(checklist.aliases) ? checklist.aliases : [],
    // Extra everyday names used only to find the checklist from a question.
    searchAliases: searchNames(checklist, synonymGroups),
    sections: Array.isArray(checklist.sections) ? checklist.sections : [],
    active: checklist.status === "active" && checklist.active !== false,
    status: ["needs_review", "hidden"].includes(checklist.status)
      ? checklist.status
      : "active",
    // Drafts written from non-standard pages carry a note for the reviewer.
    draft: checklist.draft === true,
    reviewNote:
      typeof checklist.reviewNote === "string"
        ? checklist.reviewNote.slice(0, 500)
        : "",
    reviewReasons: reviewReasons(checklist),
    // "same" = published automatically because the new edition is identical.
    versionMatch: versionResult(checklist),
    autoPublished: checklist.autoPublished === true,
    autoGenerated: checklist.autoGenerated === true,
    editedByAdmin: checklist.editedByAdmin === true,
    source: {
      filename: checklist.source?.filename || "",
      page: Number(checklist.source?.page || checklist.page || 0) || null,
      pdfRef: pdfRefForDocumentId(String(checklist.documentId || ""), {
        storageRoot: originalStorageRoot,
      }),
    },
  };
}

module.exports = { toPublicChecklist };
