const crypto = require("node:crypto");

// A new upload of a handbook gets a new document_id, so a checklist of the new
// edition is compared with the checklists of earlier editions by what it says,
// never by document_id, page or file name:
//   same    - same kind of document, same title, and the automatically
//             extracted content (sections, labels, types, every detail line,
//             every number) is identical to a checklist that was public
//             -> published again (with that checklist's administrator edits)
//   anything else stays "검토 필요" with the reason recorded:
//   changed, new, ambiguous, previous-not-public, previous-unverifiable.

/** Which handbook a file is, from its name: 검사 및 시술 / 수술 / neither. */
function checklistDocumentKind(filename = "") {
  const name = String(filename).normalize("NFC");
  if (/검사\s*및\s*시술/u.test(name)) return "procedure";
  if (/수술/u.test(name)) return "surgery";
  return null;
}

function normalizeText(value = "") {
  return String(value).normalize("NFKC").replace(/\s+/gu, " ").trim();
}

function identityKey(checklist = {}) {
  return normalizeText(checklist.title).replace(/\s+/gu, "").toLowerCase();
}

/**
 * Fingerprint of a checklist's content. Ids, page, file name and dates are
 * left out on purpose (they change with every edition); every visible word
 * and number, the order and the structure are included.
 */
function contentFingerprint(checklist = {}) {
  const shape = [
    normalizeText(checklist.title),
    (checklist.aliases || []).map(normalizeText),
    (checklist.sections || []).map((section) => [
      normalizeText(section.title),
      (section.items || []).map((item) => [
        item.type,
        normalizeText(item.label),
        (item.details || []).map(normalizeText),
        Array.isArray(item.detailCheckable) ? item.detailCheckable : null,
      ]),
    ]),
  ];
  return crypto
    .createHash("sha256")
    .update(JSON.stringify(shape))
    .digest("hex");
}

/**
 * Fingerprint of what the extractor originally produced for a stored
 * checklist. Checklists saved before this feature have none: their current
 * content still is the extraction unless an administrator edited it or it is
 * a hand-written draft, in which case the source cannot be verified.
 */
function sourceFingerprintOf(checklist = {}) {
  if (typeof checklist.sourceFingerprint === "string")
    return checklist.sourceFingerprint;
  if (checklist.editedByAdmin || checklist.draft) return null;
  if (checklist.autoGenerated === false) return null;
  return contentFingerprint(checklist);
}

function isPublic(checklist = {}) {
  return checklist.status === "active" && checklist.active !== false;
}

/**
 * Decides how a newly extracted checklist relates to earlier editions.
 * `existing` is every stored checklist; `duplicateInDocument` is true when the
 * new document yields more than one checklist with the same title.
 */
function matchPreviousVersion(
  checklist,
  existing = [],
  { duplicateInDocument = false } = {}
) {
  const kind = checklistDocumentKind(checklist?.source?.filename);
  const key = identityKey(checklist);
  const candidates = existing.filter(
    (other) =>
      other &&
      String(other.documentId) !== String(checklist.documentId) &&
      identityKey(other) === key &&
      checklistDocumentKind(other.source?.filename) === kind
  );
  const result = (code, previous = null) => ({
    result: code,
    previousId: previous?.id || null,
    previousDocumentId: previous ? String(previous.documentId) : null,
    previous,
  });

  if (!kind || !key) return result("new");
  if (duplicateInDocument) return result("ambiguous");
  if (!candidates.length) return result("new");

  const published = candidates.filter(isPublic);
  if (!published.length) return result("previous-not-public", candidates[0]);

  const sources = new Set(published.map(sourceFingerprintOf));
  if (sources.has(null)) return result("previous-unverifiable", published[0]);
  if (sources.size > 1) return result("ambiguous", published[0]);

  const newSource = contentFingerprint(checklist);
  if (!sources.has(newSource)) return result("changed", published[0]);

  // Several earlier editions may carry the same source; their visible
  // (possibly administrator-edited) content must agree as well.
  const visible = new Set(published.map(contentFingerprint));
  if (visible.size > 1) return result("ambiguous", published[0]);
  return result("same", published[0]);
}

module.exports = {
  checklistDocumentKind,
  contentFingerprint,
  identityKey,
  matchPreviousVersion,
  sourceFingerprintOf,
};
