const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const {
  isRenalBiopsyChecklistCandidate,
  extractRenalBiopsyChecklist,
  sourceContains,
} = require("../../../utils/documentChecklists/extractor");

const sourceText = fs.readFileSync(
  path.join(__dirname, "fixtures", "renal-biopsy-page-56.txt"),
  "utf8"
);

function item(checklist, label) {
  return checklist.sections
    .flatMap((section) => section.items)
    .find((entry) => entry.label === label);
}

test("Renal biopsy p.56 is detected and split into the original two sections", () => {
  assert.equal(isRenalBiopsyChecklistCandidate(sourceText), true);
  const checklist = extractRenalBiopsyChecklist({
    documentId: "renal-document",
    filename: "검사 및 시술(26.04.07).pdf",
    page: 56,
    text: sourceText,
  });

  assert.ok(checklist);
  assert.equal(checklist.source.page, 56);
  assert.deepEqual(
    checklist.sections.map((section) => section.title),
    ["검사 전", "검사 후"]
  );
  assert.equal(checklist.status, "active");
  assert.equal(checklist.autoGenerated, true);
  assert.equal(checklist.editedByAdmin, false);
});

test("only explicit action rows are checkable and purpose stays informational", () => {
  const checklist = extractRenalBiopsyChecklist({
    documentId: "renal-document",
    filename: "검사 및 시술(26.04.07).pdf",
    page: 56,
    text: sourceText,
  });

  assert.equal(item(checklist, "검사목적").type, "informational");
  for (const label of [
    "동의서",
    "금식여부",
    "IV line",
    "검사 전 준비",
    "Prepare",
    "검사장소/이동수단",
    "식이",
    "자세",
    "X-ray 및 Lab",
    "관찰사항",
  ]) {
    assert.equal(item(checklist, label).type, "checkable", label);
  }
});

test("numbered consent content remains details under one checkbox", () => {
  const checklist = extractRenalBiopsyChecklist({
    documentId: "renal-document",
    filename: "검사 및 시술(26.04.07).pdf",
    page: 56,
    text: sourceText,
  });
  const consent = item(checklist, "동의서");

  assert.equal(
    checklist.sections
      .flatMap((section) => section.items)
      .filter((entry) => entry.label === "동의서").length,
    1
  );
  assert.equal(consent.details.length, 2);
  assert.match(consent.details[0], /^①/);
  assert.match(consent.details[1], /^②/);
});

test("every automatic label and detail is present in normalized source", () => {
  const checklist = extractRenalBiopsyChecklist({
    documentId: "renal-document",
    filename: "검사 및 시술(26.04.07).pdf",
    page: 56,
    text: sourceText,
  });

  for (const section of checklist.sections) {
    assert.equal(sourceContains(sourceText, section.title), true, section.title);
    for (const entry of section.items) {
      assert.equal(sourceContains(sourceText, entry.label), true, entry.label);
      for (const detail of entry.details) {
        assert.equal(sourceContains(sourceText, detail), true, detail);
      }
    }
  }
});

test("non-checklist pages and wrong pages do not create a checklist", () => {
  assert.equal(isRenalBiopsyChecklistCandidate("일반 검사 설명 페이지"), false);
  assert.equal(
    extractRenalBiopsyChecklist({
      documentId: "renal-document",
      filename: "검사 및 시술(26.04.07).pdf",
      page: 87,
      text: sourceText,
    }),
    null
  );
});
