const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const {
  createChecklistRepository,
} = require("../../../utils/documentChecklists/repository");
const {
  toPublicChecklist,
} = require("../../../utils/documentChecklists/presenter");

function sampleChecklist() {
  return {
    version: 1,
    id: "opaque-checklist",
    documentId: "internal-document-id",
    page: 56,
    title: "신장조직검사 Renal biopsy",
    aliases: ["renal biopsy", "신생검"],
    sections: [
      {
        id: "before",
        title: "검사 전",
        items: [
          {
            id: "purpose",
            type: "informational",
            label: "검사목적",
            details: ["원문 설명"],
          },
        ],
      },
    ],
    source: { filename: "검사 및 시술(26.04.07).pdf", page: 56 },
    status: "active",
    active: true,
    autoGenerated: true,
    editedByAdmin: false,
    createdAt: "2026-09-26T00:00:00.000Z",
    updatedAt: "2026-09-26T00:00:00.000Z",
  };
}

test("automatic checklist is persisted as one opaque JSON file and is idempotent", () => {
  const storageRoot = fs.mkdtempSync(path.join(os.tmpdir(), "schat-checklist-"));
  const repository = createChecklistRepository({ storageRoot });
  const checklist = sampleChecklist();

  const first = repository.saveAutoChecklist(checklist);
  const second = repository.saveAutoChecklist({
    ...checklist,
    updatedAt: "2026-09-26T01:00:00.000Z",
  });
  const files = fs.readdirSync(storageRoot).filter((name) => name.endsWith(".json"));

  assert.equal(first.created, true);
  assert.equal(second.created, false);
  assert.equal(files.length, 1);
  assert.doesNotMatch(files[0], /internal-document-id/);
  assert.equal(repository.findByDocumentIds(["internal-document-id"]).length, 1);
});

test("administrator edits change only checklist JSON and are not overwritten automatically", () => {
  const storageRoot = fs.mkdtempSync(path.join(os.tmpdir(), "schat-checklist-"));
  const repository = createChecklistRepository({ storageRoot });
  const checklist = sampleChecklist();
  repository.saveAutoChecklist(checklist);

  const updated = repository.updateChecklist(checklist.id, {
    title: "관리자 수정 제목",
    aliases: checklist.aliases,
    sections: checklist.sections,
  });
  const replay = repository.saveAutoChecklist(checklist);

  assert.equal(updated.editedByAdmin, true);
  assert.equal(replay.created, false);
  assert.equal(repository.getById(checklist.id).title, "관리자 수정 제목");
});

test("public checklist omits internal identifiers and paths while exposing pdfRef", () => {
  const originalStorageRoot = fs.mkdtempSync(
    path.join(os.tmpdir(), "schat-original-")
  );
  const checklist = sampleChecklist();
  const output = toPublicChecklist(checklist, { originalStorageRoot });
  const serialized = JSON.stringify(output);

  assert.equal(output.id, checklist.id);
  assert.equal(output.source.page, 56);
  assert.equal(typeof output.source.pdfRef, "string");
  assert.equal(output.source.pdfRef.length, 43);
  assert.doesNotMatch(serialized, /internal-document-id/);
  assert.doesNotMatch(serialized, /storage|path/i);
});

test("invalid administrator item types are rejected", () => {
  const storageRoot = fs.mkdtempSync(path.join(os.tmpdir(), "schat-checklist-"));
  const repository = createChecklistRepository({ storageRoot });
  const checklist = sampleChecklist();
  repository.saveAutoChecklist(checklist);

  assert.throws(
    () =>
      repository.updateChecklist(checklist.id, {
        title: checklist.title,
        aliases: checklist.aliases,
        sections: [
          {
            ...checklist.sections[0],
            items: [{ ...checklist.sections[0].items[0], type: "clinical" }],
          },
        ],
      }),
    /Invalid checklist item type/
  );
});
