-- Account deletion keeps issue reports (reporter link becomes NULL, the
-- name/number/department snapshot stays) and removes the account's own
-- notifications. Table rebuild generated by prisma migrate diff; all rows
-- are copied with their ids.

-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_schat_issue_reports" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "reporter_user_id" INTEGER,
    "reporter_name" TEXT,
    "employee_number" TEXT,
    "department_name" TEXT,
    "reporter_role" TEXT,
    "category" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "related_feature" TEXT,
    "related_faq_id" INTEGER,
    "related_faq_title" TEXT,
    "status" TEXT NOT NULL DEFAULT 'open',
    "resolution" TEXT,
    "handled_by_user_id" INTEGER,
    "in_progress_at" DATETIME,
    "resolved_at" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastUpdatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "schat_issue_reports_reporter_user_id_fkey" FOREIGN KEY ("reporter_user_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "schat_issue_reports_handled_by_user_id_fkey" FOREIGN KEY ("handled_by_user_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_schat_issue_reports" ("category", "content", "createdAt", "department_name", "employee_number", "handled_by_user_id", "id", "in_progress_at", "lastUpdatedAt", "related_faq_id", "related_faq_title", "related_feature", "reporter_name", "reporter_role", "reporter_user_id", "resolution", "resolved_at", "status", "title") SELECT "category", "content", "createdAt", "department_name", "employee_number", "handled_by_user_id", "id", "in_progress_at", "lastUpdatedAt", "related_faq_id", "related_faq_title", "related_feature", "reporter_name", "reporter_role", "reporter_user_id", "resolution", "resolved_at", "status", "title" FROM "schat_issue_reports";
DROP TABLE "schat_issue_reports";
ALTER TABLE "new_schat_issue_reports" RENAME TO "schat_issue_reports";
CREATE INDEX "schat_issue_reports_reporter_user_id_idx" ON "schat_issue_reports"("reporter_user_id");
CREATE INDEX "schat_issue_reports_status_idx" ON "schat_issue_reports"("status");
CREATE TABLE "new_schat_user_notifications" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "user_id" INTEGER NOT NULL,
    "report_id" INTEGER,
    "kind" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "read_at" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "schat_user_notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "schat_user_notifications_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "schat_issue_reports" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_schat_user_notifications" ("createdAt", "id", "kind", "message", "read_at", "report_id", "user_id") SELECT "createdAt", "id", "kind", "message", "read_at", "report_id", "user_id" FROM "schat_user_notifications";
DROP TABLE "schat_user_notifications";
ALTER TABLE "new_schat_user_notifications" RENAME TO "schat_user_notifications";
CREATE INDEX "schat_user_notifications_user_id_read_at_idx" ON "schat_user_notifications"("user_id", "read_at");
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;

